function wx = angular_rate_wx_fcn(R,vy)
%ANGULAR_RATE_WX_FCN
%    WX = ANGULAR_RATE_WX_FCN(R,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Aug-2018 10:15:51

wx = -vy./R;
