function wx = angular_rate_wx_fcn(R,vy)
%ANGULAR_RATE_WX_FCN
%    WX = ANGULAR_RATE_WX_FCN(R,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Jan-2019 13:05:19

wx = -vy./R;
