function wy = angular_rate_wy_fcn(R,vx)
%ANGULAR_RATE_WY_FCN
%    WY = ANGULAR_RATE_WY_FCN(R,VX)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Dec-2018 13:41:42

wy = vx./R;
