function wx = angular_rate_wx_fcn(R,vy)
%ANGULAR_RATE_WX_FCN
%    WX = ANGULAR_RATE_WX_FCN(R,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Dec-2018 13:41:42

wx = -vy./R;
