function wy = angular_rate_wy_fcn(R,vx)
%ANGULAR_RATE_WY_FCN
%    WY = ANGULAR_RATE_WY_FCN(R,VX)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Aug-2018 10:15:51

wy = vx./R;
