function friction_required = friction_required_fcn(I,R,ax,ay)
%FRICTION_REQUIRED_FCN
%    FRICTION_REQUIRED = FRICTION_REQUIRED_FCN(I,R,AX,AY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-Dec-2018 10:17:47

t2 = I.^2;
t3 = 1.0./R.^4;
friction_required = sqrt(ax.^2.*t2.*t3+ay.^2.*t2.*t3);
