function out1 = full_contact_velocity_fcn(R,ax,ay,jx,jy,thetadot,theta,vx,vy)
%FULL_CONTACT_VELOCITY_FCN
%    OUT1 = FULL_CONTACT_VELOCITY_FCN(R,AX,AY,JX,JY,THETADOT,THETA,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Dec-2018 13:20:31

t2 = abs(ax);
t3 = abs(ay);
t4 = cos(theta);
t5 = t2.^2;
t6 = t3.^2;
t7 = t5+t6;
t8 = 1.0./sqrt(t7);
t9 = 1.0./t7.^(3.0./2.0);
t10 = R.*t4.*t8;
t11 = sign(ay);
t12 = sin(theta);
t13 = sign(ax);
out1 = [vx-jx.*(t10-R.*ax.*t2.*t4.*t9.*t13)+R.*ax.*t8.*t12.*thetadot+R.*ax.*jy.*t3.*t4.*t9.*t11,vy-jy.*(t10-R.*ay.*t3.*t4.*t9.*t11)+R.*ay.*t8.*t12.*thetadot+R.*ay.*jx.*t2.*t4.*t9.*t13,R.*t4.*thetadot];
