function out1 = full_contact_velocity_fcn(R,ax,ay,jx,jy,thetadot,theta,vx,vy)
%FULL_CONTACT_VELOCITY_FCN
%    OUT1 = FULL_CONTACT_VELOCITY_FCN(R,AX,AY,JX,JY,THETADOT,THETA,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-Dec-2018 10:17:49

t2 = cos(theta);
if ((ax ~= 0.0) & (ay ~= 0.0))
    t0 = 1.0./(ax.^2+ay.^2).^(3.0./2.0).*(vx.*(ax.^2+ay.^2).^(3.0./2.0)-R.*ay.^2.*jx.*t2+R.*ax.^3.*thetadot.*sin(theta)+R.*ax.*ay.^2.*thetadot.*sin(theta)+R.*ax.*ay.*jy.*t2);
else
    t0 = NaN;
end
if ((ax ~= 0.0) & (ay ~= 0.0))
    t1 = 1.0./(ax.^2+ay.^2).^(3.0./2.0).*(vy.*(ax.^2+ay.^2).^(3.0./2.0)-R.*ax.^2.*jy.*t2+R.*ay.^3.*thetadot.*sin(theta)+R.*ax.^2.*ay.*thetadot.*sin(theta)+R.*ax.*ay.*jx.*t2);
else
    t1 = NaN;
end
out1 = [t0,t1,R.*t2.*thetadot];
