function out1 = isurf_fcn(ax,ay,theta)
%ISURF_FCN
%    OUT1 = ISURF_FCN(AX,AY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    07-Aug-2018 13:41:59

t2 = cos(theta);
t3 = abs(t2);
t4 = 1.0./t3;
t5 = ax.^2;
t6 = ay.^2;
t7 = t5+t6;
t8 = 1.0./sqrt(t7);
out1 = [-ay.*t2.*t4.*t8,ax.*t2.*t4.*t8,0.0];
