function friction_actual_max = max_available_friction_fcn(I,R,ax,ay,fric_coeff,g,m,theta)
%MAX_AVAILABLE_FRICTION_FCN
%    FRICTION_ACTUAL_MAX = MAX_AVAILABLE_FRICTION_FCN(I,R,AX,AY,FRIC_COEFF,G,M,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Feb-2019 09:13:47

t4 = R.^2;
t5 = m.*t4;
t2 = I+t5;
t3 = 1.0./R.^4;
t6 = t2.^2;
friction_actual_max = fric_coeff.*(g.*m+(sin(theta).*sqrt(ax.^2.*t3.*t6+ay.^2.*t3.*t6))./cos(theta));
