function out1 = pusher_linear_acceleration_fcn(R,ax,ay,jx,jy,pusherX,pusherY,pusherZ,rx,ry,sx,sy,thetadot,theta,thetadotdot,vx,vy)
%PUSHER_LINEAR_ACCELERATION_FCN
%    OUT1 = PUSHER_LINEAR_ACCELERATION_FCN(R,AX,AY,JX,JY,PUSHERX,PUSHERY,PUSHERZ,RX,RY,SX,SY,THETADOT,THETA,THETADOTDOT,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    09-Jan-2019 09:46:56

t2 = cos(theta);
t3 = ax.^2;
t4 = ay.^2;
t5 = t3+t4;
t6 = sin(theta);
t7 = t2.^2;
t8 = 1.0./t5;
t9 = 1.0./sqrt(t5);
t10 = R.*ay.*t2.*t9;
t11 = pusherY-ry+t10;
t12 = 1.0./t5.^(3.0./2.0);
t13 = R.*t6;
t14 = R-pusherZ+t13;
t15 = theta.*2.0;
t16 = sin(t15);
t17 = ax.*jy;
t19 = ay.*jx;
t18 = t17-t19;
t20 = t6.^2;
t21 = ax.*t3.*thetadot;
t22 = ax.*t4.*thetadot;
t23 = (ax.*ay.*jy.*t16)./2.0;
t26 = (jx.*t4.*t16)./2.0;
t24 = t21+t22+t23-t26;
t25 = 1.0./t5.^(5.0./2.0);
t27 = 1.0./t5.^2;
t28 = t6+1.0;
t29 = R.*ax.*t2.*t9;
t30 = pusherX-rx+t29;
t31 = ax.*ay.*t2.*t6.*t12.*t14;
t32 = cos(t15);
t33 = t6-t6.*t20;
t34 = ay.*t4.*thetadot.*2.0;
t35 = ay.*t3.*thetadot.*2.0;
t36 = ax.*ay.*jx.*t16;
t38 = jy.*t3.*t16;
t37 = t34+t35+t36-t38;
t39 = R.*ax.*ay.*t2.*t7.*t18.*t25;
t40 = t3.^2;
t41 = t4.^2;
t42 = jy.^2;
t43 = jx.^2;
t44 = thetadot.^2;
t45 = sqrt(t5);
t46 = t5.^(3.0./2.0);
out1 = [ax.*t28+jx.*(t39-t12.*t14.*(t3.*thetadot.*3.0+t4.*thetadot+(ay.*jy.*t16)./2.0)+ax.*t14.*t24.*t25.*3.0-jy.*t7.*t8.*t11+ax.*t7.*t11.*t18.*t27.*2.0)+jy.*(-t12.*t14.*(ax.*ay.*thetadot.*2.0+(ax.*jy.*t16)./2.0-ay.*jx.*t16)+ay.*t14.*t24.*t25.*3.0+jx.*t7.*t8.*t11+ay.*t7.*t11.*t18.*t27.*2.0-R.*t2.*t3.*t7.*t18.*t25)+thetadot.*(t2.*vx-R.*t2.*t12.*t24+t8.*t11.*t16.*t18+R.*ay.*t12.*t18.*t33-ay.*t12.*t14.*t18.*t32)-sy.*(t31+ax.*t7.*t8.*t11)+sx.*(ay.*t7.*t8.*t11+t2.*t4.*t6.*t12.*t14)-ax.*t9.*t14.*thetadotdot+t7.*t8.*t18.*vy,ay.*t28-jy.*(t39+(t12.*t14.*(t3.*thetadot.*2.0+t4.*thetadot.*6.0+ax.*jx.*t16))./2.0-ay.*t14.*t25.*t37.*(3.0./2.0)+jx.*t7.*t8.*t30+ay.*t7.*t18.*t27.*t30.*2.0)+jx.*(t12.*t14.*(ax.*ay.*thetadot.*4.0-ax.*jy.*t16.*2.0+ay.*jx.*t16).*(-1.0./2.0)+ax.*t14.*t25.*t37.*(3.0./2.0)+jy.*t7.*t8.*t30-ax.*t7.*t18.*t27.*t30.*2.0+R.*t2.*t4.*t7.*t18.*t25)-thetadot.*(-t2.*vy+(R.*t2.*t12.*t37)./2.0+t8.*t16.*t18.*t30+R.*ax.*t12.*t18.*t33-ax.*t12.*t14.*t18.*t32)-sx.*(t31+ay.*t7.*t8.*t30)+sy.*(ax.*t7.*t8.*t30+t2.*t3.*t6.*t12.*t14)-ay.*t9.*t14.*thetadotdot-t7.*t8.*t18.*vx,(t25.*(t2.*t3.*t40.*2.0+t2.*t3.*t41.*6.0+t2.*t4.*t40.*6.0+t2.*t4.*t41.*2.0-ax.*pusherX.*t40.*thetadotdot.*2.0-ax.*pusherX.*t41.*thetadotdot.*2.0-ay.*pusherY.*t40.*thetadotdot.*2.0-ay.*pusherY.*t41.*thetadotdot.*2.0+ax.*rx.*t40.*thetadotdot.*2.0+ax.*rx.*t41.*thetadotdot.*2.0+ay.*ry.*t40.*thetadotdot.*2.0+ay.*ry.*t41.*thetadotdot.*2.0+ax.*t40.*thetadot.*vx.*2.0+ax.*t41.*thetadot.*vx.*2.0+ay.*t40.*thetadot.*vy.*2.0+ay.*t41.*thetadot.*vy.*2.0-jx.*pusherX.*t41.*thetadot.*2.0-jy.*pusherY.*t40.*thetadot.*2.0+jx.*rx.*t41.*thetadot.*2.0+jy.*ry.*t40.*thetadot.*2.0+jx.*t2.*t41.*vx.*2.0-jx.*t16.*t41.*vx+jy.*t2.*t40.*vy.*2.0-jy.*t16.*t40.*vy+pusherX.*sx.*t16.*t41+pusherY.*sy.*t16.*t40-rx.*sx.*t16.*t41-ry.*sy.*t16.*t40+R.*t6.*t40.*t44.*t45.*2.0+R.*t6.*t41.*t44.*t45.*2.0-R.*t2.*t3.*t46.*thetadotdot.*2.0-R.*t2.*t4.*t46.*thetadotdot.*2.0-ax.*pusherX.*t3.*t16.*t42+ax.*pusherX.*t4.*t16.*t42.*2.0-ax.*pusherX.*t4.*t16.*t43.*3.0-ay.*pusherY.*t3.*t16.*t42.*3.0+ay.*pusherY.*t3.*t16.*t43.*2.0-ay.*pusherY.*t4.*t16.*t43-ax.*pusherX.*t3.*t4.*thetadotdot.*4.0-ay.*pusherY.*t3.*t4.*thetadotdot.*4.0+ax.*rx.*t3.*t16.*t42-ax.*rx.*t4.*t16.*t42.*2.0+ax.*rx.*t4.*t16.*t43.*3.0+ay.*ry.*t3.*t16.*t42.*3.0-ay.*ry.*t3.*t16.*t43.*2.0+ay.*ry.*t4.*t16.*t43+ax.*rx.*t3.*t4.*thetadotdot.*4.0+ay.*ry.*t3.*t4.*thetadotdot.*4.0+ax.*t3.*t4.*thetadot.*vx.*4.0-ax.*t6.*t40.*thetadot.*vx.*2.0-ax.*t6.*t41.*thetadot.*vx.*2.0+ay.*t3.*t4.*thetadot.*vy.*4.0-ay.*t6.*t40.*thetadot.*vy.*2.0-ay.*t6.*t41.*thetadot.*vy.*2.0-jx.*pusherX.*t3.*t4.*thetadot.*2.0+jx.*pusherX.*t32.*t41.*thetadot.*2.0-jy.*pusherY.*t3.*t4.*thetadot.*2.0+jy.*pusherY.*t32.*t40.*thetadot.*2.0+jx.*rx.*t3.*t4.*thetadot.*2.0-jx.*rx.*t32.*t41.*thetadot.*2.0+jy.*ry.*t3.*t4.*thetadot.*2.0-jy.*ry.*t32.*t40.*thetadot.*2.0+jx.*t2.*t3.*t4.*vx.*2.0-jx.*t3.*t4.*t16.*vx+jy.*t2.*t3.*t4.*vy.*2.0-jy.*t3.*t4.*t16.*vy+pusherX.*sx.*t3.*t4.*t16+pusherY.*sy.*t3.*t4.*t16-rx.*sx.*t3.*t4.*t16-ry.*sy.*t3.*t4.*t16-ax.*t3.*t4.*t6.*thetadot.*vx.*4.0-ay.*t3.*t4.*t6.*thetadot.*vy.*4.0+jx.*pusherX.*t3.*t4.*t32.*thetadot.*2.0+jy.*pusherY.*t3.*t4.*t32.*thetadot.*2.0-jx.*rx.*t3.*t4.*t32.*thetadot.*2.0-jy.*ry.*t3.*t4.*t32.*thetadot.*2.0+ax.*ay.*jx.*pusherY.*t3.*thetadot.*2.0+ax.*ay.*jx.*pusherY.*t4.*thetadot.*2.0+ax.*ay.*jy.*pusherX.*t3.*thetadot.*2.0+ax.*ay.*jy.*pusherX.*t4.*thetadot.*2.0-ax.*ay.*jx.*ry.*t3.*thetadot.*2.0-ax.*ay.*jy.*rx.*t3.*thetadot.*2.0-ax.*ay.*jx.*ry.*t4.*thetadot.*2.0-ax.*ay.*jy.*rx.*t4.*thetadot.*2.0-ax.*ay.*jx.*t2.*t3.*vy.*2.0-ax.*ay.*jy.*t2.*t3.*vx.*2.0-ax.*ay.*jx.*t2.*t4.*vy.*2.0-ax.*ay.*jy.*t2.*t4.*vx.*2.0+ax.*ay.*jx.*t3.*t16.*vy+ax.*ay.*jy.*t3.*t16.*vx+ax.*ay.*jx.*t4.*t16.*vy+ax.*ay.*jy.*t4.*t16.*vx-ax.*ay.*pusherY.*sx.*t3.*t16-ax.*jx.*jy.*pusherY.*t3.*t16.*2.0-ax.*ay.*pusherY.*sx.*t4.*t16+ax.*jx.*jy.*pusherY.*t4.*t16.*4.0-ax.*ay.*pusherX.*sy.*t3.*t16+ay.*jx.*jy.*pusherX.*t3.*t16.*4.0-ax.*ay.*pusherX.*sy.*t4.*t16-ay.*jx.*jy.*pusherX.*t4.*t16.*2.0+ax.*ay.*rx.*sy.*t3.*t16+ax.*ay.*ry.*sx.*t3.*t16+ax.*jx.*jy.*ry.*t3.*t16.*2.0-ay.*jx.*jy.*rx.*t3.*t16.*4.0+ax.*ay.*rx.*sy.*t4.*t16+ax.*ay.*ry.*sx.*t4.*t16-ax.*jx.*jy.*ry.*t4.*t16.*4.0+ay.*jx.*jy.*rx.*t4.*t16.*2.0+R.*t3.*t4.*t6.*t44.*t45.*4.0-ax.*ay.*jx.*pusherY.*t3.*t32.*thetadot.*2.0-ax.*ay.*jx.*pusherY.*t4.*t32.*thetadot.*2.0-ax.*ay.*jy.*pusherX.*t3.*t32.*thetadot.*2.0-ax.*ay.*jy.*pusherX.*t4.*t32.*thetadot.*2.0+ax.*ay.*jx.*ry.*t3.*t32.*thetadot.*2.0+ax.*ay.*jy.*rx.*t3.*t32.*thetadot.*2.0+ax.*ay.*jx.*ry.*t4.*t32.*thetadot.*2.0+ax.*ay.*jy.*rx.*t4.*t32.*thetadot.*2.0))./2.0];
