function out1 = pusher_angular_acceleration_fcn(ax,ay,jx,jy,sx,sy,thetadot,theta,thetadotdot)
%PUSHER_ANGULAR_ACCELERATION_FCN
%    OUT1 = PUSHER_ANGULAR_ACCELERATION_FCN(AX,AY,JX,JY,SX,SY,THETADOT,THETA,THETADOTDOT)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    09-Jan-2019 09:46:57

t2 = ay.^2;
t3 = t2.^2;
t4 = ax.^2;
t5 = theta.*2.0;
t6 = sin(t5);
t7 = t4.^2;
t8 = jx.^2;
t9 = cos(t5);
t10 = t2+t4;
t11 = 1.0./t10.^(5.0./2.0);
t12 = jy.^2;
t13 = cos(theta);
t14 = t13.^2;
t15 = 1.0./t10.^2;
t16 = 1.0./t10;
out1 = [t11.*(ay.*t3.*thetadotdot.*2.0+ay.*t7.*thetadotdot.*2.0+jy.*t7.*thetadot.*2.0-sy.*t6.*t7+ay.*t2.*t6.*t8-ay.*t4.*t6.*t8.*2.0+ay.*t4.*t6.*t12.*3.0+ay.*t2.*t4.*thetadotdot.*4.0+jy.*t2.*t4.*thetadot.*2.0-jy.*t7.*t9.*thetadot.*2.0-sy.*t2.*t4.*t6-ax.*ay.*jx.*t2.*thetadot.*2.0-ax.*ay.*jx.*t4.*thetadot.*2.0+ax.*ay.*sx.*t2.*t6-ax.*jx.*jy.*t2.*t6.*4.0+ax.*ay.*sx.*t4.*t6+ax.*jx.*jy.*t4.*t6.*2.0-jy.*t2.*t4.*t9.*thetadot.*2.0+ax.*ay.*jx.*t2.*t9.*thetadot.*2.0+ax.*ay.*jx.*t4.*t9.*thetadot.*2.0).*(-1.0./2.0),(t11.*(ax.*t3.*thetadotdot.*2.0+ax.*t7.*thetadotdot.*2.0+jx.*t3.*thetadot.*2.0-sx.*t3.*t6+ax.*t2.*t6.*t8.*3.0-ax.*t2.*t6.*t12.*2.0+ax.*t4.*t6.*t12+ax.*t2.*t4.*thetadotdot.*4.0+jx.*t2.*t4.*thetadot.*2.0-jx.*t3.*t9.*thetadot.*2.0-sx.*t2.*t4.*t6-ax.*ay.*jy.*t2.*thetadot.*2.0-ax.*ay.*jy.*t4.*thetadot.*2.0+ax.*ay.*sy.*t2.*t6+ay.*jx.*jy.*t2.*t6.*2.0+ax.*ay.*sy.*t4.*t6-ay.*jx.*jy.*t4.*t6.*4.0-jx.*t2.*t4.*t9.*thetadot.*2.0+ax.*ay.*jy.*t2.*t9.*thetadot.*2.0+ax.*ay.*jy.*t4.*t9.*thetadot.*2.0))./2.0,jx.*t14.*t15.*(jy.*t2-jy.*t4+ax.*ay.*jx.*2.0)-jy.*t14.*t15.*(-jx.*t2+jx.*t4+ax.*ay.*jy.*2.0)+ax.*sy.*t14.*t16-ay.*sx.*t14.*t16-t6.*t16.*thetadot.*(ax.*jy-ay.*jx)];
