function out1 = pusher_angular_velocity_fcn(ax,ay,jx,jy,thetadot,theta)
%PUSHER_ANGULAR_VELOCITY_FCN
%    OUT1 = PUSHER_ANGULAR_VELOCITY_FCN(AX,AY,JX,JY,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Jan-2019 13:05:21

t2 = ay.^2;
t3 = ax.^2;
t4 = theta.*2.0;
t5 = sin(t4);
t6 = t2+t3;
t7 = 1.0./t6.^(3.0./2.0);
t8 = cos(theta);
out1 = [t7.*(ay.*t2.*thetadot.*2.0+ay.*t3.*thetadot.*2.0-jy.*t3.*t5+ax.*ay.*jx.*t5).*(-1.0./2.0),t7.*(ax.*t2.*thetadot+ax.*t3.*thetadot-(jx.*t2.*t5)./2.0+(ax.*ay.*jy.*t5)./2.0),(t8.^2.*(ax.*jy-ay.*jx))./t6];
