function out1 = pusher_angular_velocity_fcn(ax,ay,jx,jy,thetadot,theta)
%PUSHER_ANGULAR_VELOCITY_FCN
%    OUT1 = PUSHER_ANGULAR_VELOCITY_FCN(AX,AY,JX,JY,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Dec-2018 13:41:43

if ((ax ~= 0.0) & (ay ~= 0.0))
    t0 = 1.0./(ax.^2+ay.^2).^(3.0./2.0).*(ay.^3.*thetadot.*2.0-ax.^2.*jy.*sin(theta.*2.0)+ax.^2.*ay.*thetadot.*2.0+ax.*ay.*jx.*sin(theta.*2.0)).*(-1.0./2.0);
else
    t0 = NaN;
end
if ((ax ~= 0.0) & (ay ~= 0.0))
    t1 = 1.0./(ax.^2+ay.^2).^(3.0./2.0).*(ax.^3.*thetadot-ay.^2.*jx.*sin(theta.*2.0).*(1.0./2.0)+ax.*ay.^2.*thetadot+ax.*ay.*jy.*sin(theta.*2.0).*(1.0./2.0));
else
    t1 = NaN;
end
if ((ax ~= 0.0) & (ay ~= 0.0))
    t2 = (cos(theta).^2.*(ax.*jy-ay.*jx))./(ax.^2+ay.^2);
else
    t2 = NaN;
end
out1 = [t0,t1,t2];
