function ball_surface_vel_rel_world = world_contact_velocity_fcn(ax,ay,theta,vx,vy)
%WORLD_CONTACT_VELOCITY_FCN
%    BALL_SURFACE_VEL_REL_WORLD = WORLD_CONTACT_VELOCITY_FCN(AX,AY,THETA,VX,VY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Jan-2019 13:05:20

t2 = sin(theta);
t3 = abs(ax);
t4 = abs(ay);
t5 = cos(theta);
t6 = t3.^2;
t7 = t4.^2;
t8 = t6+t7;
t9 = 1.0./sqrt(t8);
ball_surface_vel_rel_world = [vx+t2.*vx;vy+t2.*vy;ax.*t5.*t9.*vx+ay.*t5.*t9.*vy];
